[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --workspace=backend --include=dev"]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npx tsc"
]

[start]
cmd = "node backend/dist/index.js"
