[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --workspace=backend"]

[phases.build]
cmds = [
  "npm run db:generate --workspace=backend",
  "npm run build --workspace=backend"
]

[start]
cmd = "node backend/dist/index.js"
